language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install -qq
    libmysqlclient-dev
    automake
script:
  - cd judger-v2
  - ./configure && make
  - cd ../dispatcher-v2
  - ./configure && make
